import React from 'react'
import ReactDOM from 'react-dom/client'
import Overlay from './Overlay'
import './index.css'

declare const chrome: any;


// Create Shadow Host
const host = document.createElement('div');
host.id = 'hiremax-overlay-host';
host.style.position = 'fixed';
host.style.bottom = '0px';
host.style.right = '0px';
host.style.zIndex = '2147483647'; // Max Z-Index
host.style.pointerEvents = 'none'; // Pass through clicks by default (Overlay container will re-enable)

document.body.appendChild(host);

// Create Shadow Root
const shadow = host.attachShadow({ mode: 'open' });

// Inject Styles (Need to fetch the CSS file generated by Vite)
// Logic: We will inject the <link> tag pointing to the extension resource
// The filename is predictable: overlay.css (from vite build)
const styleLink = document.createElement('link');
styleLink.rel = 'stylesheet';
styleLink.href = chrome.runtime.getURL('dist/overlay/overlay.css');
shadow.appendChild(styleLink);

// Create Root Element
const rootDiv = document.createElement('div');
rootDiv.id = 'root';
shadow.appendChild(rootDiv);

ReactDOM.createRoot(rootDiv).render(
    <React.StrictMode>
        <Overlay />
    </React.StrictMode>,
)
