export type JobState = 'active' | 'cooling' | 'disappeared' | 'reposted' | 'zombie';

export type RawJob = {
  externalId: string;
  title: string;
  companyName: string;
  companySlug: string;
  locationName: string;
  sourceUrl: string;
  postedAt?: string;
  description?: string;
  source: string;
  rawData: Record<string, unknown>;
};

export type ParsedJob = {
  role_category: string;
  seniority_band: string;
  location_type: string;
  is_remote: boolean;
  is_tech: boolean;
  salary_min?: number;
  salary_max?: number;
  salary_currency: string;
  total_comp_min?: number;
  total_comp_max?: number;
  equity_type: string;
  bonus_mentioned: boolean;
  pay_transparency: boolean;
  tech_stack: string[];
  requirements: string[];
  benefits: string[];
  skills: string[];
  years_exp_min?: number;
  years_exp_max?: number;
  degree_required: boolean;
  contract_type: string;
  work_model: string;
  hybrid_days_onsite?: number;
  timezone_required?: string;
  relocation_offered: boolean;
  visa_sponsorship: boolean;
  visa_types: string[];
  authorized_only: boolean;
  clearance_required: boolean;
  clearance_level: string;
  ats_type: string;
  easy_apply: boolean;
  cover_letter_required: boolean;
  portfolio_required: boolean;
  industry: string;
  company_about?: string;
};

export type NormalizedJob = {
  fingerprint: string;
  canonical_hash: string;
  company_slug: string;
  title: string;
  company_name: string;
  location_name: string;
  location_type: string;
  is_remote: boolean;
  is_tech: boolean;
  source: string;
  source_url: string;
  external_id: string;
  posted_at?: string;
  role_category: string;
  seniority_band: string;
  industry: string;
  salary_min?: number;
  salary_max?: number;
  salary_currency: string;
  total_comp_min?: number;
  total_comp_max?: number;
  equity_type: string;
  bonus_mentioned: boolean;
  pay_transparency: boolean;
  tech_stack: string[];
  requirements: string[];
  benefits: string[];
  skills: string[];
  years_exp_min?: number;
  years_exp_max?: number;
  degree_required: boolean;
  contract_type: string;
  work_model: string;
  hybrid_days_onsite?: number;
  timezone_required?: string;
  relocation_offered: boolean;
  visa_sponsorship: boolean;
  visa_types: string[];
  authorized_only: boolean;
  clearance_required: boolean;
  clearance_level: string;
  ats_type: string;
  easy_apply: boolean;
  cover_letter_required: boolean;
  portfolio_required: boolean;
  application_deadline?: string;
  quality_score: number;   // float 0.0-1.0 ALWAYS
  quality_factors?: Record<string, number>;
  job_state: JobState;
  last_seen_at: string;
  first_seen_at?: string;  // only set on INSERT, omit on UPDATE
};

export type RunResult = {
  source: string;
  companySlug: string;
  jobsFetched: number;
  jobsInserted: number;
  jobsUpdated: number;
  jobsDisappeared: number;
  errors: string[];
  durationMs: number;
  fullSweepComplete: boolean;
};
