
import React from 'react';
import { AppView } from '../types';
import { ArrowLeft } from 'lucide-react';

interface TermsViewProps {
  setView?: (v: AppView) => void;
}

export const TermsView: React.FC<TermsViewProps> = ({ setView }) => {
  return (
    <div className="min-h-screen bg-[#0B0F1A]">
      <div className="max-w-3xl mx-auto px-6 py-20">
        {setView && (
          <button
            onClick={() => setView('landing')}
            className="flex items-center gap-2 text-slate-400 hover:text-white text-sm font-bold uppercase tracking-widest transition-colors mb-12"
          >
            <ArrowLeft size={16} /> Back to Home
          </button>
        )}

        <div className="mb-12">
          <p className="text-blue-500 text-xs font-black uppercase tracking-[0.3em] mb-3">Legal</p>
          <h1 className="text-5xl font-black text-white tracking-tighter leading-none mb-4">Terms & Conditions</h1>
          <p className="text-slate-400 text-base font-medium">Last Updated: May 18, 2025 &nbsp;·&nbsp; Effective Immediately</p>
        </div>

        <div className="space-y-10 text-slate-300 leading-relaxed text-[15px]">

          <section>
            <h2 className="text-white font-black text-xl mb-3">1. Agreement to Terms</h2>
            <p>By accessing or using HireMax ("the Service"), you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you do not have permission to access the Service. HireMax is a digital career intelligence product operated by HireMax Technologies.</p>
          </section>

          <section>
            <h2 className="text-white font-black text-xl mb-3">2. Description of Service</h2>
            <p>HireMax is an AI-powered career platform that provides users with resume analysis, resume rebuilding, interview preparation, cover letter generation, application tracking, LinkedIn optimization, and market intelligence tools. All services are delivered entirely digitally. <strong className="text-white">Delivery is instantaneous upon successful payment verification.</strong></p>
          </section>

          <section>
            <h2 className="text-white font-black text-xl mb-3">3. Eligibility</h2>
            <p>You must be at least 16 years of age to use this Service. By using HireMax, you represent and warrant that you are of legal age to form a binding contract and meet all eligibility requirements.</p>
          </section>

          <section>
            <h2 className="text-white font-black text-xl mb-3">4. User Accounts</h2>
            <p>You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately at <a href="mailto:hiremax.ai@gmail.com" className="text-blue-400 hover:text-blue-300 underline">hiremax.ai@gmail.com</a> of any unauthorized use of your account. HireMax reserves the right to terminate accounts that violate these Terms.</p>
          </section>

          <section>
            <h2 className="text-white font-black text-xl mb-3">5. Intellectual Property</h2>
            <p>All content, features, functionality, AI models, algorithms, and output generated by the HireMax platform are owned by HireMax Technologies and are protected by applicable intellectual property laws. The reports and resume documents generated for you are licensed for your personal, non-commercial use only. You may not resell, redistribute, or represent AI-generated content as entirely human-authored work without appropriate disclosure.</p>
          </section>

          <section>
            <h2 className="text-white font-black text-xl mb-3">6. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc ml-6 mt-3 space-y-2 text-slate-300">
              <li>Submit false, misleading, or fraudulent resume information</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Attempt to reverse-engineer, scrape, or copy any part of the platform</li>
              <li>Harass, abuse, or harm other users or HireMax staff</li>
              <li>Use automated bots or scrapers against the platform</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-black text-xl mb-3">7. Payments & Subscriptions</h2>
            <p>Paid plans are billed on a monthly or one-time basis as selected at checkout. All prices are in US Dollars (USD). By subscribing, you authorize us to charge your payment method on a recurring basis until you cancel. You may cancel at any time from your account settings. Cancellation takes effect at the end of the current billing period. Please review our <strong className="text-white">Refund Policy</strong> for all sales terms.</p>
          </section>

          <section>
            <h2 className="text-white font-black text-xl mb-3">8. Disclaimers</h2>
            <p>HireMax provides career intelligence tools and analysis. We do not guarantee employment, interview success, or specific career outcomes. AI-generated output is intended to assist your job search and should be reviewed by you before submission to employers. The Service is provided "as is" and "as available" without warranties of any kind, express or implied.</p>
          </section>

          <section>
            <h2 className="text-white font-black text-xl mb-3">9. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, HireMax Technologies shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or career opportunities, arising from your use of or inability to use the Service.</p>
          </section>

          <section>
            <h2 className="text-white font-black text-xl mb-3">10. Termination</h2>
            <p>We reserve the right to suspend or terminate your access to HireMax at any time, with or without notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties, or for any other reason at our discretion.</p>
          </section>

          <section>
            <h2 className="text-white font-black text-xl mb-3">11. Governing Law</h2>
            <p>These Terms are governed by and construed in accordance with applicable laws. Any disputes arising under these Terms will be resolved through binding arbitration or in a court of competent jurisdiction.</p>
          </section>

          <section>
            <h2 className="text-white font-black text-xl mb-3">12. Changes to Terms</h2>
            <p>We reserve the right to modify these Terms at any time. We will notify users of material changes by updating the "Last Updated" date above. Continued use of the Service after changes constitutes acceptance of the revised Terms.</p>
          </section>

          <section>
            <h2 className="text-white font-black text-xl mb-3">13. Contact</h2>
            <p>For questions about these Terms, contact us at: <a href="mailto:hiremax.ai@gmail.com" className="text-blue-400 hover:text-blue-300 underline">hiremax.ai@gmail.com</a></p>
          </section>

        </div>
      </div>
    </div>
  );
};

export default TermsView;
