-- 20260401_intelligence_outcomes.sql
-- Goal: Outcome Logging & Bayesian Intelligence Layer

-- 1. APPLICATION OUTCOMES (The Feedback Loop)
CREATE TABLE IF NOT EXISTS public.application_outcomes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    pipeline_run_id UUID REFERENCES public.pipeline_runs(id), -- Nullable if not generated by us
    job_pointer_id UUID REFERENCES public.job_pointers(id),
    company TEXT NOT NULL,
    role TEXT NOT NULL,
    outcome TEXT CHECK (outcome IN ('applied', 'interview', 'rejected', 'ghosted', 'offer')),
    response_time_days INTEGER, -- Days from application to outcome
    feature_vector JSONB DEFAULT '{}', -- Snapshot of features at time of outcome
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. BAYESIAN PRIORS (Success Probabilities)
-- Stores the learned weights for different features per industry/domain
CREATE TABLE IF NOT EXISTS public.bayesian_priors (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    feature_name TEXT NOT NULL, -- e.g., 'verb_tier_ratio', 'metric_density'
    category_id TEXT NOT NULL, -- e.g., 'FINTECH', 'FAANG', 'STARTUP'
    prior_mean FLOAT DEFAULT 0.5,
    prior_variance FLOAT DEFAULT 0.25,
    sample_size INTEGER DEFAULT 0,
    last_updated_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(feature_name, category_id)
);

-- 3. FUNCTION: Update Bayesian Priors
-- WHY: Implements Step 2 (Feature Correlation) - Heuristic Weighting
CREATE OR REPLACE FUNCTION public.update_prior_on_outcome(
    p_feature_name TEXT,
    p_category_id TEXT,
    p_success BOOLEAN
) RETURNS VOID AS $$
DECLARE
    v_inc FLOAT := CASE WHEN p_success THEN 0.1 ELSE -0.05 END;
BEGIN
    INSERT INTO public.bayesian_priors (feature_name, category_id, prior_mean, sample_size)
    VALUES (p_feature_name, p_category_id, 0.5 + v_inc, 1)
    ON CONFLICT (feature_name, category_id) DO UPDATE SET
        prior_mean = GREATEST(0.0, LEAST(1.0, bayesian_priors.prior_mean + v_inc / (bayesian_priors.sample_size + 1))),
        sample_size = bayesian_priors.sample_size + 1,
        last_updated_at = now();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. VIEW: Intelligence Dashboard
CREATE OR REPLACE VIEW public.view_intelligence_efficiency AS
SELECT 
    company,
    role,
    outcome,
    count(*) as total,
    round(avg(response_time_days), 1) as avg_response_days
FROM public.application_outcomes
GROUP BY company, role, outcome;

-- RLS: Only users can see their own outcomes
ALTER TABLE public.application_outcomes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own outcomes" ON public.application_outcomes
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own outcomes" ON public.application_outcomes
    FOR INSERT WITH CHECK (auth.uid() = user_id);
